<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Agar.Sample.Hotfix.V2</AssemblyName>
    <RootNamespace>Agar.Sample.Hotfix.V2</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Shared/Shared.csproj" />
    <ProjectReference Include="../../../../src/ULinkGame.Server.Hotfix.Abstractions/ULinkGame.Server.Hotfix.Abstractions.csproj" />
  </ItemGroup>
</Project>
