<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Agar.Sample.State</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../../src/ULinkGame.Server/ULinkGame.Server.csproj" />
        <ProjectReference Include="../State.Contracts/State.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Program.cs" />
        <Compile Remove="Persistence\**\*.cs" />
        <None Remove="appsettings.json" />
    </ItemGroup>

</Project>
