using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ULinkGame.Server.Hotfix.Generators
{
    [Generator]
    public sealed class HotfixGenerator : IIncrementalGenerator
    {
        private const string HotfixStateAttributeName = "ULinkGame.Server.Hotfix.Abstractions.HotfixStateAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var states = context.SyntaxProvider
                .CreateSyntaxProvider(
                    IsStateCandidate,
                    GetState)
                .Where(IsNotNull);

            context.RegisterSourceOutput(states, GenerateState);
        }

        private static bool IsStateCandidate(SyntaxNode node, CancellationToken cancellationToken)
        {
            return node is ClassDeclarationSyntax declaration && declaration.AttributeLists.Count > 0;
        }

        private static HotfixStateInfo? GetState(GeneratorSyntaxContext context, CancellationToken cancellationToken)
        {
            var declaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(declaration, cancellationToken);
            if (symbol == null)
            {
                return null;
            }

            var hasAttribute = symbol.GetAttributes().Any(attribute =>
                attribute.AttributeClass != null &&
                attribute.AttributeClass.ToDisplayString() == HotfixStateAttributeName);

            return hasAttribute ? new HotfixStateInfo(symbol, declaration) : null;
        }

        private static bool IsNotNull(HotfixStateInfo? state)
        {
            return state != null;
        }

        private static void GenerateState(SourceProductionContext context, HotfixStateInfo? state)
        {
            if (state == null)
            {
                return;
            }

            if (!state.Declaration.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword)))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    HotfixGeneratorDiagnostics.StateMustBePartial,
                    state.Declaration.Identifier.GetLocation(),
                    state.Symbol.ToDisplayString()));
                return;
            }

            var hintName = CreateHintName(state.Symbol);
            context.AddSource(hintName, SourceText.From(GenerateStateSource(state), Encoding.UTF8));
        }

        private static string GenerateStateSource(HotfixStateInfo state)
        {
            var namespaceName = state.Symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : state.Symbol.ContainingNamespace.ToDisplayString();

            var fields = state.Symbol.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(field => field.DeclaredAccessibility == Accessibility.Private)
                .OrderBy(field => field.Locations.Length == 0 ? 0 : field.Locations[0].SourceSpan.Start)
                .ToArray();

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System.ComponentModel;");
            builder.AppendLine();

            if (namespaceName != null)
            {
                builder.Append("namespace ").Append(namespaceName).AppendLine();
                builder.AppendLine("{");
            }

            AppendStateType(builder, state.Symbol, fields, namespaceName != null ? 1 : 0);

            if (namespaceName != null)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        private static void AppendStateType(StringBuilder builder, INamedTypeSymbol stateType, IFieldSymbol[] fields, int indentLevel)
        {
            var indent = new string(' ', indentLevel * 4);
            var usedAccessorNames = new HashSet<string>();

            builder.Append(indent).Append("partial class ").Append(stateType.Name).AppendLine();
            builder.Append(indent).AppendLine("{");

            foreach (var field in fields)
            {
                var accessorName = CreateUniqueAccessorName(field.Name, usedAccessorNames);

                builder.Append(indent).AppendLine("    [EditorBrowsable(EditorBrowsableState.Never)]");
                builder.Append(indent).Append("    public ")
                    .Append(field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    .Append(' ')
                    .Append(accessorName)
                    .AppendLine("()");
                builder.Append(indent).AppendLine("    {");
                builder.Append(indent).Append("        return ").Append(EscapeIdentifier(field.Name)).AppendLine(";");
                builder.Append(indent).AppendLine("    }");
                builder.AppendLine();
            }

            builder.Append(indent).AppendLine("}");
        }

        private static string CreateUniqueAccessorName(string fieldName, HashSet<string> usedAccessorNames)
        {
            var normalizedName = fieldName.TrimStart('_');
            if (normalizedName.Length == 0)
            {
                normalizedName = fieldName;
            }

            var candidate = "__hotfix_" + SanitizeIdentifierPart(normalizedName);
            if (usedAccessorNames.Add(candidate))
            {
                return candidate;
            }

            candidate = "__hotfix_" + SanitizeIdentifierPart(fieldName);
            if (usedAccessorNames.Add(candidate))
            {
                return candidate;
            }

            var suffix = 2;
            while (!usedAccessorNames.Add(candidate + "_" + suffix))
            {
                suffix++;
            }

            return candidate + "_" + suffix;
        }

        private static string SanitizeIdentifierPart(string value)
        {
            var builder = new StringBuilder();
            foreach (var character in value)
            {
                if (builder.Length == 0)
                {
                    builder.Append(SyntaxFacts.IsIdentifierStartCharacter(character) ? character : '_');
                    continue;
                }

                builder.Append(SyntaxFacts.IsIdentifierPartCharacter(character) ? character : '_');
            }

            return builder.Length == 0 ? "field" : builder.ToString();
        }

        private static string EscapeIdentifier(string identifier)
        {
            return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None
                ? identifier
                : "@" + identifier;
        }

        private static string CreateHintName(INamedTypeSymbol symbol)
        {
            return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", string.Empty)
                .Replace('.', '_')
                .Replace('<', '_')
                .Replace('>', '_')
                .Replace(',', '_')
                .Replace(' ', '_') + ".Hotfix.g.cs";
        }

        private sealed class HotfixStateInfo
        {
            public HotfixStateInfo(INamedTypeSymbol symbol, ClassDeclarationSyntax declaration)
            {
                Symbol = symbol;
                Declaration = declaration;
            }

            public INamedTypeSymbol Symbol { get; }

            public ClassDeclarationSyntax Declaration { get; }
        }
    }
}
