using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ULinkGame.Server.Hotfix.Generators
{
    [Generator]
    public sealed class HotfixGenerator : IIncrementalGenerator
    {
        private const string HotfixStateAttributeName = "ULinkGame.Server.Hotfix.Abstractions.HotfixStateAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var states = context.SyntaxProvider
                .CreateSyntaxProvider(
                    IsStateCandidate,
                    GetState)
                .Where(IsNotNull);

            context.RegisterSourceOutput(states, GenerateState);
        }

        private static bool IsStateCandidate(SyntaxNode node, CancellationToken cancellationToken)
        {
            return node is TypeDeclarationSyntax declaration && declaration.AttributeLists.Count > 0;
        }

        private static HotfixStateInfo? GetState(GeneratorSyntaxContext context, CancellationToken cancellationToken)
        {
            var declaration = (TypeDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(declaration, cancellationToken);
            if (symbol == null)
            {
                return null;
            }

            var hasAttribute = symbol.GetAttributes().Any(attribute =>
                attribute.AttributeClass != null &&
                attribute.AttributeClass.ToDisplayString() == HotfixStateAttributeName);

            return hasAttribute ? new HotfixStateInfo(symbol, declaration) : null;
        }

        private static bool IsNotNull(HotfixStateInfo? state)
        {
            return state != null;
        }

        private static void GenerateState(SourceProductionContext context, HotfixStateInfo? state)
        {
            if (state == null)
            {
                return;
            }

            if (!state.Declaration.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword)))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    HotfixGeneratorDiagnostics.StateMustBePartial,
                    state.Declaration.Identifier.GetLocation(),
                    state.Symbol.ToDisplayString()));
                return;
            }

            var nonPartialContainer = state.ContainingTypes.FirstOrDefault(type => !IsPartial(type.Declaration));
            if (nonPartialContainer != null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    HotfixGeneratorDiagnostics.ContainingTypeMustBePartial,
                    nonPartialContainer.Declaration.Identifier.GetLocation(),
                    nonPartialContainer.Symbol.ToDisplayString(),
                    state.Symbol.ToDisplayString()));
                return;
            }

            var hintName = CreateHintName(state.Symbol);
            context.AddSource(hintName, SourceText.From(GenerateStateSource(state), Encoding.UTF8));
        }

        private static bool IsPartial(TypeDeclarationSyntax declaration)
        {
            return declaration.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword));
        }

        private static string GenerateStateSource(HotfixStateInfo state)
        {
            var namespaceName = state.Symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : state.Symbol.ContainingNamespace.ToDisplayString();

            var fields = state.Symbol.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(IsFriendAccessorField)
                .OrderBy(field => field.Locations.Length == 0 ? 0 : field.Locations[0].SourceSpan.Start)
                .ToArray();

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System.ComponentModel;");
            builder.AppendLine();

            if (namespaceName != null)
            {
                builder.Append("namespace ").Append(namespaceName).AppendLine();
                builder.AppendLine("{");
            }

            AppendContainingTypes(builder, state, fields, namespaceName != null ? 1 : 0);

            if (namespaceName != null)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        private static bool IsFriendAccessorField(IFieldSymbol field)
        {
            return field.DeclaredAccessibility == Accessibility.Private &&
                !field.IsImplicitlyDeclared &&
                field.AssociatedSymbol == null &&
                !field.IsStatic &&
                !field.IsConst;
        }

        private static void AppendContainingTypes(StringBuilder builder, HotfixStateInfo state, IFieldSymbol[] fields, int indentLevel)
        {
            foreach (var containingType in state.ContainingTypes)
            {
                AppendTypeHeader(builder, containingType.Declaration, indentLevel);
                builder.Append(new string(' ', indentLevel * 4)).AppendLine("{");
                indentLevel++;
            }

            AppendStateType(builder, state.Declaration, fields, indentLevel);

            for (var index = state.ContainingTypes.Length - 1; index >= 0; index--)
            {
                indentLevel--;
                builder.Append(new string(' ', indentLevel * 4)).AppendLine("}");
            }
        }

        private static void AppendStateType(StringBuilder builder, TypeDeclarationSyntax declaration, IFieldSymbol[] fields, int indentLevel)
        {
            var indent = new string(' ', indentLevel * 4);
            var usedAccessorNames = new HashSet<string>();
            var normalizedNameCounts = fields
                .GroupBy(field => NormalizeFieldName(field.Name))
                .ToDictionary(group => group.Key, group => group.Count());

            AppendTypeHeader(builder, declaration, indentLevel);
            builder.Append(indent).AppendLine("{");

            foreach (var field in fields)
            {
                var accessorName = CreateUniqueAccessorName(field.Name, normalizedNameCounts, usedAccessorNames);

                builder.Append(indent).AppendLine("    [EditorBrowsable(EditorBrowsableState.Never)]");
                builder.Append(indent).Append("    public ")
                    .Append(field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    .Append(' ')
                    .Append(accessorName)
                    .AppendLine("()");
                builder.Append(indent).AppendLine("    {");
                builder.Append(indent).Append("        return ").Append(EscapeIdentifier(field.Name)).AppendLine(";");
                builder.Append(indent).AppendLine("    }");
                builder.AppendLine();
            }

            builder.Append(indent).AppendLine("    [EditorBrowsable(EditorBrowsableState.Never)]");
            builder.Append(indent).AppendLine("    public static string __hotfix_dispatch_marker()");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        return typeof(global::ULinkGame.Server.Hotfix.Dispatch.HotfixDispatch).FullName ?? string.Empty;");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();

            builder.Append(indent).AppendLine("}");
        }

        private static void AppendTypeHeader(StringBuilder builder, TypeDeclarationSyntax declaration, int indentLevel)
        {
            builder.Append(new string(' ', indentLevel * 4))
                .Append(GetTypeModifiers(declaration))
                .Append(' ')
                .Append(declaration.Keyword.ValueText)
                .Append(' ')
                .Append(declaration.Identifier.ValueText)
                .Append(declaration.TypeParameterList != null ? declaration.TypeParameterList.ToString() : string.Empty)
                .AppendLine();

            foreach (var constraint in declaration.ConstraintClauses)
            {
                builder.Append(new string(' ', (indentLevel + 1) * 4))
                    .AppendLine(constraint.ToString());
            }
        }

        private static string GetTypeModifiers(TypeDeclarationSyntax declaration)
        {
            return string.Join(" ", declaration.Modifiers.Select(modifier => modifier.ValueText));
        }

        private static string CreateUniqueAccessorName(
            string fieldName,
            Dictionary<string, int> normalizedNameCounts,
            HashSet<string> usedAccessorNames)
        {
            var normalizedName = NormalizeFieldName(fieldName);
            if (fieldName.StartsWith("_", System.StringComparison.Ordinal) &&
                normalizedNameCounts.TryGetValue(normalizedName, out var count) &&
                count > 1)
            {
                normalizedName = fieldName;
            }

            var candidate = "__hotfix_" + SanitizeIdentifierPart(normalizedName);
            if (usedAccessorNames.Add(candidate))
            {
                return candidate;
            }

            candidate = "__hotfix_" + SanitizeIdentifierPart(fieldName.TrimStart('@'));
            if (usedAccessorNames.Add(candidate))
            {
                return candidate;
            }

            var suffix = 2;
            while (!usedAccessorNames.Add(candidate + "_" + suffix))
            {
                suffix++;
            }

            return candidate + "_" + suffix;
        }

        private static string NormalizeFieldName(string fieldName)
        {
            var normalizedName = fieldName.TrimStart('_');
            return normalizedName.Length == 0 ? fieldName : normalizedName;
        }

        private static string SanitizeIdentifierPart(string value)
        {
            var builder = new StringBuilder();
            foreach (var character in value)
            {
                if (builder.Length == 0)
                {
                    builder.Append(SyntaxFacts.IsIdentifierStartCharacter(character) ? character : '_');
                    continue;
                }

                builder.Append(SyntaxFacts.IsIdentifierPartCharacter(character) ? character : '_');
            }

            return builder.Length == 0 ? "field" : builder.ToString();
        }

        private static string EscapeIdentifier(string identifier)
        {
            return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None
                ? identifier
                : "@" + identifier;
        }

        private static string CreateHintName(INamedTypeSymbol symbol)
        {
            return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", string.Empty)
                .Replace('.', '_')
                .Replace('<', '_')
                .Replace('>', '_')
                .Replace(',', '_')
                .Replace(' ', '_') + ".Hotfix.g.cs";
        }

        private sealed class HotfixStateInfo
        {
            public HotfixStateInfo(INamedTypeSymbol symbol, TypeDeclarationSyntax declaration)
            {
                Symbol = symbol;
                Declaration = declaration;
                ContainingTypes = CreateContainingTypes(symbol, declaration);
            }

            public INamedTypeSymbol Symbol { get; }

            public TypeDeclarationSyntax Declaration { get; }

            public ContainingTypeInfo[] ContainingTypes { get; }

            private static ContainingTypeInfo[] CreateContainingTypes(INamedTypeSymbol symbol, TypeDeclarationSyntax declaration)
            {
                var containingDeclarations = new List<TypeDeclarationSyntax>();
                for (var current = declaration.Parent; current != null; current = current.Parent)
                {
                    if (current is TypeDeclarationSyntax containingDeclaration)
                    {
                        containingDeclarations.Add(containingDeclaration);
                    }
                }

                containingDeclarations.Reverse();

                var containingSymbols = new List<INamedTypeSymbol>();
                for (var current = symbol.ContainingType; current != null; current = current.ContainingType)
                {
                    containingSymbols.Add(current);
                }

                containingSymbols.Reverse();

                return containingDeclarations
                    .Zip(containingSymbols, (typeDeclaration, typeSymbol) => new ContainingTypeInfo(typeSymbol, typeDeclaration))
                    .ToArray();
            }
        }

        private sealed class ContainingTypeInfo
        {
            public ContainingTypeInfo(INamedTypeSymbol symbol, TypeDeclarationSyntax declaration)
            {
                Symbol = symbol;
                Declaration = declaration;
            }

            public INamedTypeSymbol Symbol { get; }

            public TypeDeclarationSyntax Declaration { get; }
        }
    }
}
