<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Gateway</RootNamespace>
    <ULinkRPCGenerateServer>true</ULinkRPCGenerateServer>
    <ULinkRPCServerGeneratedNamespace>Gateway.Generated</ULinkRPCServerGeneratedNamespace>
  </PropertyGroup>

    <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <ProjectReference Include="../State.Contracts/State.Contracts.csproj" />
    <ProjectReference Include="../State/State.csproj" />
    <ProjectReference Include="../Hotfix/Agar.Sample.Hotfix.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\..\src\ULinkGame.Server\ULinkGame.Server.csproj" />
    <ProjectReference Include="..\..\..\..\src\ULinkGame.Server.Hotfix\ULinkGame.Server.Hotfix.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ULinkRPC.Server" Version="0.11.9" />
    <PackageReference Include="ULinkRPC.Analyzers" Version="0.1.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ULinkRPC.Serializer.MemoryPack" Version="0.11.1" />
    <PackageReference Include="ULinkRPC.Transport.Kcp" Version="0.11.11" />
    <PackageReference Include="ULinkRPC.Transport.WebSocket" Version="0.11.6" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
