<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Gateway</RootNamespace>
  </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <ProjectReference Include="../State.Contracts/State.Contracts.csproj" />
    <ProjectReference Include="../State/State.csproj" />
    <ProjectReference Include="..\..\..\..\src\ULinkGame.Server\ULinkGame.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ULinkRPC.Server" Version="0.11.9" />
    <PackageReference Include="ULinkRPC.Transport.Kcp" Version="0.11.10" />
    <PackageReference Include="ULinkRPC.Transport.WebSocket" Version="0.11.6" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
