<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Agar.Godot</RootNamespace>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <BuildInParallel>false</BuildInParallel>
    <RestoreBuildInParallel>false</RestoreBuildInParallel>
    <ULinkRPCGenerateClient>true</ULinkRPCGenerateClient>
    <ULinkRPCGeneratedNamespace>Rpc.Generated</ULinkRPCGeneratedNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ULinkRPC.Core" Version="0.11.8" />
    <PackageReference Include="ULinkRPC.Client" Version="0.11.4" />
    <PackageReference Include="ULinkRPC.Analyzers" Version="0.1.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ULinkRPC.Serializer.MemoryPack" Version="0.11.1" />
    <PackageReference Include="ULinkRPC.Transport.Kcp" Version="0.11.11" />
    <PackageReference Include="ULinkRPC.Transport.WebSocket" Version="0.11.6" />
    <ProjectReference Include="../../../src/ULinkGame.Client/ULinkGame.Client.csproj" />
    <ProjectReference Include="../Shared/Shared.csproj" TargetFramework="net8.0">
      <SetTargetFramework>TargetFramework=net8.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>
