**

!NuGet.config
!Directory.Build.props

!src/
!src/ULinkGame.Server/
!src/ULinkGame.Server/**

!samples/
!samples/Agar.Unity/
!samples/Agar.Unity/Shared/
!samples/Agar.Unity/Shared/**
!samples/Agar.Unity/Server/
!samples/Agar.Unity/Server/**

**/.idea/
**/.vs/
**/bin/
**/obj/
**/Library/
**/Logs/
**/Temp/
**/UserSettings/
